package com.pigai.entity;
// default package
// Generated 2015-4-17 0:44:39 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Courseware generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "t_courseware", catalog = "pigai")
public class Courseware implements java.io.Serializable {

	private Integer coursewareId;
	private Course Course;
	private File File;

	public Courseware() {
	}

	public Courseware(Course Course, File File) {
		this.Course = Course;
		this.File = File;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "coursewareId", unique = true, nullable = false)
	public Integer getCoursewareId() {
		return this.coursewareId;
	}

	public void setCoursewareId(Integer coursewareId) {
		this.coursewareId = coursewareId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "courseId", nullable = false)
	public Course getTCourse() {
		return this.Course;
	}

	public void setTCourse(Course Course) {
		this.Course = Course;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fileId", nullable = false)
	public File getTFile() {
		return this.File;
	}

	public void setTFile(File File) {
		this.File = File;
	}

}
