package com.pigai.entity;

// default package
// Generated 2015-5-9 15:06:17 by Hibernate Tools 4.3.1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Courseware generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "courseware", catalog = "pigai")
public class Courseware implements java.io.Serializable {

	private Integer coursewareId;
	private Course course;
	private Fileinfo fileinfo;
	private Date createTime;
	private String courseName;

	public Courseware() {
	}

	public Courseware(Course course, Fileinfo fileinfo, Date createTime,
			String courseName) {
		this.course = course;
		this.fileinfo = fileinfo;
		this.createTime = createTime;
		this.courseName = courseName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "coursewareId", unique = true, nullable = false)
	public Integer getCoursewareId() {
		return this.coursewareId;
	}

	public void setCoursewareId(Integer coursewareId) {
		this.coursewareId = coursewareId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "courseId", nullable = false)
	public Course getCourse() {
		return this.course;
	}

	public void setCourse(Course course) {
		this.course = course;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fileId", nullable = false)
	public Fileinfo getFileinfo() {
		return this.fileinfo;
	}

	public void setFileinfo(Fileinfo fileinfo) {
		this.fileinfo = fileinfo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createTime", nullable = false, length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "courseName", nullable = false)
	public String getCourseName() {
		return this.courseName;
	}

	public void setCourseName(String courseName) {
		this.courseName = courseName;
	}

}
