package com.pigai.entity;

// default package
// Generated 2015-5-9 15:06:17 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Course generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "course", catalog = "pigai")
public class Course implements java.io.Serializable {

	private Integer courseId;
	private Teacher teacher;
	private String courseName;
	private String courseIntr;
	private Date createTime;
	private String teacherName;
	private byte finished;
	private Set<Homework> homeworks = new HashSet<Homework>(0);
	private Set<Courseware> coursewares = new HashSet<Courseware>(0);
	private Set<Selectcourse> selectcourses = new HashSet<Selectcourse>(0);

	public Course() {
	}

	public Course(Teacher teacher, String courseName, Date createTime,
			String teacherName, byte finished) {
		this.teacher = teacher;
		this.courseName = courseName;
		this.createTime = createTime;
		this.teacherName = teacherName;
		this.finished = finished;
	}

	public Course(Teacher teacher, String courseName, String courseIntr,
			Date createTime, String teacherName, byte finished,
			Set<Homework> homeworks, Set<Courseware> coursewares,
			Set<Selectcourse> selectcourses) {
		this.teacher = teacher;
		this.courseName = courseName;
		this.courseIntr = courseIntr;
		this.createTime = createTime;
		this.teacherName = teacherName;
		this.finished = finished;
		this.homeworks = homeworks;
		this.coursewares = coursewares;
		this.selectcourses = selectcourses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "courseId", unique = true, nullable = false)
	public Integer getCourseId() {
		return this.courseId;
	}

	public void setCourseId(Integer courseId) {
		this.courseId = courseId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "teacherId", nullable = false)
	public Teacher getTeacher() {
		return this.teacher;
	}

	public void setTeacher(Teacher teacher) {
		this.teacher = teacher;
	}

	@Column(name = "courseName", nullable = false, length = 50)
	public String getCourseName() {
		return this.courseName;
	}

	public void setCourseName(String courseName) {
		this.courseName = courseName;
	}

	@Column(name = "courseIntr", length = 50)
	public String getCourseIntr() {
		return this.courseIntr;
	}

	public void setCourseIntr(String courseIntr) {
		this.courseIntr = courseIntr;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createTime", nullable = false, length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "teacherName", nullable = false, length = 50)
	public String getTeacherName() {
		return this.teacherName;
	}

	public void setTeacherName(String teacherName) {
		this.teacherName = teacherName;
	}

	@Column(name = "finished", nullable = false)
	public byte getFinished() {
		return this.finished;
	}

	public void setFinished(byte finished) {
		this.finished = finished;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "course")
	public Set<Homework> getHomeworks() {
		return this.homeworks;
	}

	public void setHomeworks(Set<Homework> homeworks) {
		this.homeworks = homeworks;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "course")
	public Set<Courseware> getCoursewares() {
		return this.coursewares;
	}

	public void setCoursewares(Set<Courseware> coursewares) {
		this.coursewares = coursewares;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "course")
	public Set<Selectcourse> getSelectcourses() {
		return this.selectcourses;
	}

	public void setSelectcourses(Set<Selectcourse> selectcourses) {
		this.selectcourses = selectcourses;
	}

}
