package com.pigai.entity;
// default package
// Generated 2015-4-17 0:44:39 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Homework generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "t_homework", catalog = "pigai")
public class Homework implements java.io.Serializable {

	private Integer homeworkId;
	private Course Course;
	private String name;
	private String introduction;
	private Set<Submitrecord> Submitrecords = new HashSet<Submitrecord>(0);

	public Homework() {
	}

	public Homework(Course Course, String name, String introduction) {
		this.Course = Course;
		this.name = name;
		this.introduction = introduction;
	}

	public Homework(Course Course, String name, String introduction,
			Set<Submitrecord> Submitrecords) {
		this.Course = Course;
		this.name = name;
		this.introduction = introduction;
		this.Submitrecords = Submitrecords;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "homeworkId", unique = true, nullable = false)
	public Integer geHomeworkId() {
		return this.homeworkId;
	}

	public void seHomeworkId(Integer homeworkId) {
		this.homeworkId = homeworkId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "courseId", nullable = false)
	public Course getCourse() {
		return this.Course;
	}

	public void setCourse(Course Course) {
		this.Course = Course;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "introduction", nullable = false)
	public String getIntroduction() {
		return this.introduction;
	}

	public void setIntroduction(String introduction) {
		this.introduction = introduction;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "Homework")
	public Set<Submitrecord> getSubmitrecords() {
		return this.Submitrecords;
	}

	public void setSubmitrecords(Set<Submitrecord> Submitrecords) {
		this.Submitrecords = Submitrecords;
	}

}
