package com.pigai.entity;

// default package
// Generated 2015-4-26 23:48:10 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Homework generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "homework", catalog = "pigai")
public class Homework implements java.io.Serializable {

	private Integer homeworkId;
	private Course course;
	private String name;
	private String introduction;
	private int score;
	private Set<Submitrecord> submitrecords = new HashSet<Submitrecord>(0);

	public Homework() {
	}

	public Homework(Course course, String name, String introduction, int score) {
		this.course = course;
		this.name = name;
		this.introduction = introduction;
		this.score = score;
	}

	public Homework(Course course, String name, String introduction, int score,
			Set<Submitrecord> submitrecords) {
		this.course = course;
		this.name = name;
		this.introduction = introduction;
		this.score = score;
		this.submitrecords = submitrecords;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "homeworkId", unique = true, nullable = false)
	public Integer getHomeworkId() {
		return this.homeworkId;
	}

	public void setHomeworkId(Integer homeworkId) {
		this.homeworkId = homeworkId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "courseId", nullable = false)
	public Course getCourse() {
		return this.course;
	}

	public void setCourse(Course course) {
		this.course = course;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "introduction", nullable = false)
	public String getIntroduction() {
		return this.introduction;
	}

	public void setIntroduction(String introduction) {
		this.introduction = introduction;
	}

	@Column(name = "score", nullable = false)
	public int getScore() {
		return this.score;
	}

	public void setScore(int score) {
		this.score = score;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "homework")
	public Set<Submitrecord> getSubmitrecords() {
		return this.submitrecords;
	}

	public void setSubmitrecords(Set<Submitrecord> submitrecords) {
		this.submitrecords = submitrecords;
	}

}
