package com.pigai.entity;

// default package
// Generated 2015-5-9 15:06:17 by Hibernate Tools 4.3.1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Selectcourse generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "selectcourse", catalog = "pigai")
public class Selectcourse implements java.io.Serializable {

	private Integer selectId;
	private Course course;
	private Student student;
	private int grade;
	private Date createTime;
	private String courseName;

	public Selectcourse() {
	}

	public Selectcourse(Course course, Student student, int grade,
			Date createTime, String courseName) {
		this.course = course;
		this.student = student;
		this.grade = grade;
		this.createTime = createTime;
		this.courseName = courseName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "selectId", unique = true, nullable = false)
	public Integer getSelectId() {
		return this.selectId;
	}

	public void setSelectId(Integer selectId) {
		this.selectId = selectId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "courseId", nullable = false)
	public Course getCourse() {
		return this.course;
	}

	public void setCourse(Course course) {
		this.course = course;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "studentId", nullable = false)
	public Student getStudent() {
		return this.student;
	}

	public void setStudent(Student student) {
		this.student = student;
	}

	@Column(name = "grade", nullable = false)
	public int getGrade() {
		return this.grade;
	}

	public void setGrade(int grade) {
		this.grade = grade;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createTime", nullable = false, length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "courseName", nullable = false)
	public String getCourseName() {
		return this.courseName;
	}

	public void setCourseName(String courseName) {
		this.courseName = courseName;
	}

}
