package com.pigai.entity;
// default package
// Generated 2015-4-17 0:44:39 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SelecCourse generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "t_selecCourse", catalog = "pigai")
public class Selectcourse implements java.io.Serializable {

	private Integer selectId;
	private Course Course;
	private Student Student;

	public Selectcourse() {
	}

	public Selectcourse(Course Course, Student Student) {
		this.Course = Course;
		this.Student = Student;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "selectId", unique = true, nullable = false)
	public Integer getSelectId() {
		return this.selectId;
	}

	public void setSelectId(Integer selectId) {
		this.selectId = selectId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "courseId", nullable = false)
	public Course getCourse() {
		return this.Course;
	}

	public void setCourse(Course Course) {
		this.Course = Course;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "studentId", nullable = false)
	public Student getStudent() {
		return this.Student;
	}

	public void setStudent(Student Student) {
		this.Student = Student;
	}

}
