package com.pigai.entity;

// default package
// Generated 2015-4-17 0:44:39 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Student generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "t_student", catalog = "pigai")
public class Student implements java.io.Serializable {

	private Integer studentId;
	private int studentNo;
	private String name;
	private String school;
	private String college;
	private String username;
	private String password;
	private Set<Submitrecord> Submitrecords = new HashSet<Submitrecord>(0);
	private Set<Selectcourse> Selectcourses = new HashSet<Selectcourse>(0);

	public Student() {
	}

	public Student(int studentNo, String name, String school, String college,
			String username, String password) {
		this.studentNo = studentNo;
		this.name = name;
		this.school = school;
		this.college = college;
		this.username = username;
		this.password = password;
	}

	public Student(int studentNo, String name, String school, String college,
			String username, String password,
			Set<Submitrecord> Submitrecords, Set<Selectcourse> Selectcourses) {
		this.studentNo = studentNo;
		this.name = name;
		this.school = school;
		this.college = college;
		this.username = username;
		this.password = password;
		this.Submitrecords = Submitrecords;
		this.Selectcourses = Selectcourses;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "studentId", unique = true, nullable = false)
	public Integer geStudentId() {
		return this.studentId;
	}

	public void seStudentId(Integer studentId) {
		this.studentId = studentId;
	}

	@Column(name = "studentNo", nullable = false)
	public int geStudentNo() {
		return this.studentNo;
	}

	public void seStudentNo(int studentNo) {
		this.studentNo = studentNo;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "school", nullable = false)
	public String getSchool() {
		return this.school;
	}

	public void setSchool(String school) {
		this.school = school;
	}

	@Column(name = "college", nullable = false)
	public String getCollege() {
		return this.college;
	}

	public void setCollege(String college) {
		this.college = college;
	}

	@Column(name = "username", nullable = false)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", nullable = false)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "Student")
	public Set<Submitrecord> geSubmitrecords() {
		return this.Submitrecords;
	}

	public void seSubmitrecords(Set<Submitrecord> Submitrecords) {
		this.Submitrecords = Submitrecords;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "Student")
	public Set<Selectcourse> getSelectcourses() {
		return this.Selectcourses;
	}

	public void setSelectcourses(Set<Selectcourse> Selectcourses) {
		this.Selectcourses = Selectcourses;
	}

}
